### ISSUE TITLE
add farm image in command list

### ISSUE THREAD

**Issue by jacksonmajolo** [juanpetterson/discord-bot#2]
please, you can add this image in command list

![crime](https://github.com/user-attachments/assets/daa44abf-93aa-468f-9eab-7c3a96401a40)

i suggest the name !farm

thanks a lot!

**Comment by juanpetterson** [comment]
you suggestions have been impleted and is now available on the bot. thank you for your suggestion

https://github.com/juanpetterson/discord-bot/pull/3
